services:
  - type: web
    name: pifagor-trade-website
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TELEGRAM_SIGNAL_LINK
        sync: false
      - key: TELEGRAM_LOGIN_BOT
        sync: false
      - key: GOOGLE_SCRIPT_URL
        sync: false
      - key: GOOGLE_SHEET_URL
        sync: false
      - key: API_PUBLIC_URL
        sync: false
